apiVersion: v1
kind: Service
metadata:
  name: openai-chatbot-service
  namespace: openai-chatbots
spec:
  selector:
    app: openai-chatbots
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
